# Generated by Django 5.1.4 on 2024-12-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('image_poster', models.CharField(max_length=255)),
                ('image_backdrop', models.CharField(max_length=255)),
                ('genres', models.ManyToManyField(related_name='genres', to='IMDbyx.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('id_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDbyx.actor')),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDbyx.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', through='IMDbyx.Movie_Actor', to='IMDbyx.actor'),
        ),
    ]
