# Generated by Django 5.1.4 on 2024-12-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDbyx', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
    ]
