# Generated by Django 5.1.4 on 2024-12-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDbyx', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
